version: '2'

services:
    jaeger-collector:
      image: jaegertracing/jaeger-collector
      command: ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra", "--collector.zipkin.http-port=9411"]
      ports:
        - "14269:14269"
        - "14268:14268"
        - "14267:14267"
        - "14250:14250"
        - "9411:9411"
      restart: on-failure
      depends_on:
        - cassandra-schema

    jaeger-query:
      image: jaegertracing/jaeger-query
      command: ["--cassandra.keyspace=jaeger_v1_dc1", "--cassandra.servers=cassandra"]
      ports:
        - "16686:16686/tcp"
        - "16687:16687/tcp"
      restart: on-failure
      depends_on:
        - jaeger-collector

    jaeger-agent:
      image: jaegertracing/jaeger-agent
      command: ["--reporter.grpc.host-port=jaeger-collector:14250"]
      ports:
        - "5775:5775/udp"
        - "6831:6831/udp"
        - "6832:6832/udp"
        - "5778:5778"
      restart: on-failure
      depends_on:
        - jaeger-collector

    cassandra:
      image: cassandra:3.9
      ports:
        - "7000:7000/tcp"
        - "7001:7001/tcp"
        - "7199:7199/tcp"
        - "9042:9042/tcp"
        - "9160:9160/tcp"

    cassandra-schema:
      image: jaegertracing/jaeger-cassandra-schema
      depends_on:
        - cassandra

    datadog-agent:
      image: datadog/agent:latest
      environment:
        - DD_API_KEY=${DD_API_KEY}
        - DD_APM_ENABLED=true
        - DD_APM_NON_LOCAL_TRAFFIC=true
        - DD_APM_ENV=foogaro.laptop
      ports:
        - "8125:8125/udp"
        - "8126:8126/tcp"
      restart: on-failure
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /proc/:/host/proc/:ro
        - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro

    shift-tracer:
      image: shift-tracer
      environment:
        - DD_AGENT_HOST=datadog-agent
        - DD_TRACE_AGENT_PORT=8126
        - JAEGER_AGENT_HOST=jaeger-collector
        - JAEGER_AGENT_PORT=14268
        - TRACER_NAME=DATADOG
        - JAEGER_SAMPLER_MANAGER_HOST_PORT=jaeger-agent:5778
        - JAEGER_AGENT_HOST=jaeger-agent
        - JAEGER_AGENT_PORT=6831
      ports:
        - "8080:8080/tcp"
      depends_on:
        - jaeger-collector
